# Generated by Django 2.0.2 on 2018-02-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydives_api', '0003_auto_20180220_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationinfo',
            old_name='details',
            new_name='url',
        ),
    ]
